version: 2
updates:
  - package-ecosystem: "npm"
    directory: "opa-react-demo/"
    schedule:
      interval: "daily"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "nestjs-demo/"
    schedule:
      interval: "daily"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  # TicketHub Dependencies:
  - package-ecosystem: "npm"
    directory: "/tickethub/server/node"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      prisma:
        patterns:
          - "*prisma*"
  - package-ecosystem: "gradle"
    directory: "/tickethub/server/java"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      jackson:
        patterns:
          - "com.fasterxml.jackson*"
      slf4j:
        patterns:
          - "org.slf4j:*"
    ignore: # server/java doesn't compile when bumping these
      - dependency-name: "org.eclipse.jetty:*"
      - dependency-name: "org.glassfish.jersey.*"
  - package-ecosystem: "gradle"
    directory: "/tickethub/server/springboot"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      jackson:
        patterns:
          - "com.fasterxml.jackson*"
      slf4j:
        patterns:
          - "org.slf4j:*"
  - package-ecosystem: "nuget"
    directory: "/tickethub/server/csharp"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      Microsoft:
        patterns:
          - "Microsoft*"
      Npgsql:
        patterns:
          - "Npgsql*"
  - package-ecosystem: "npm"
    directory: "/tickethub/client/react"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      react:
        patterns:
          - "react*"
  - package-ecosystem: "npm"
    directory: "/tickethub/client/html"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
  - package-ecosystem: github-actions
    directory: /tickethub/
    schedule:
      interval: daily
  - package-ecosystem: "npm"
    directory: "/tickethub/tests/e2e"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      all:
        patterns:
          - "*"
