version: 2
updates:
  - package-ecosystem: "npm"
    directory: "opa-react-demo/"
    schedule:
      interval: "daily"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "nestjs-demo/"
    schedule:
      interval: "daily"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
