version: 2
updates:
  - package-ecosystem: "npm"
    directory: "opa-react-demo/"
    schedule:
      interval: "daily"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
