services:
  react-demo:
    build: .
    expose:
    - 3000
    depends_on:
      - eopa
    command:
      - npm
      - start
    network_mode: host

  eopa:
    image: ghcr.io/styrainc/enterprise-opa:latest
    expose: 
      - 8181
    ports:
      - "8181:8181"
    command:
      - run
      - --server
      - --addr=:8181
      - --log-level=debug
      - /policies
    working_dir: /
    volumes:
      - ./policies:/policies
    environment:
      EOPA_LICENSE_KEY: ${EOPA_LICENSE_KEY}