name: CI

on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main

# When a new revision is pushed to a PR, cancel all in-progress CI runs for that
# PR. See https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  examples:
    name: build examples
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        pkg:
        - opa-react-demo
        - nestjs-demo
    steps:
      - name: Check out code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          fetch-depth: 0
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22
      - name: build and start
        run: docker compose up --build -d
        working-directory: ${{ matrix.pkg }}
      - name: integration tests
        run: docker compose run --quiet-pull integration-tests
        working-directory: ${{ matrix.pkg }}
        if: matrix.pkg == 'nestjs-demo'
      - name: dump logs
        run: docker compose logs
        if: failure()
        working-directory: ${{ matrix.pkg }}
      - name: build and start
        run: docker compose down
        working-directory: ${{ matrix.pkg }}
