name: CI

on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main

# When a new revision is pushed to a PR, cancel all in-progress CI runs for that
# PR. See https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  examples:
    name: build examples
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        pkg: [opa-react-demo]
    steps:
      - name: Check out code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0
      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: 22
      - name: build and start
        run: |
          docker compose up --build -d
          docker compose down
        working-directory: ${{ matrix.pkg }}
